import * as vscode from 'vscode';
import { Backend, createBackend, requestId, Request } from './backend';
const CAP=6000; let enabled=true; let backend:Backend; let generation=0; let output:vscode.OutputChannel; let status:vscode.StatusBarItem;
function contextFor(document:vscode.TextDocument, position:vscode.Position, scope:string){const text=document.getText(), offset=document.offsetAt(position); if(scope==='currentFile'&&text.length<=CAP)return{before:text.slice(0,offset),after:text.slice(offset)}; const start=scope==='nearby'?Math.max(0,offset-CAP/2):Math.max(0,Math.min(offset-CAP/2,text.length-CAP)),end=Math.min(text.length,start+CAP); if(scope==='currentFile')output.appendLine(`currentFile context truncated (${text.length} chars)`); return{before:text.slice(start,offset),after:text.slice(offset,end)};}
function isCredential(document:vscode.TextDocument){return /(^|\/)(\.env(?:\.[^/]+)?|[^/]+\.(?:pem|key|p12|pfx|secret|secrets))$/i.test(document.uri.fsPath);}
class Provider implements vscode.InlineCompletionItemProvider{
 async provideInlineCompletionItems(document:vscode.TextDocument,position:vscode.Position,_ctx:vscode.InlineCompletionContext,token:vscode.CancellationToken):Promise<vscode.InlineCompletionItem[]>{if(!enabled||token.isCancellationRequested||vscode.env.remoteName||vscode.env.uiKind===vscode.UIKind.Web||isCredential(document))return[]; await new Promise<void>(resolve=>{const t=setTimeout(resolve,350);token.onCancellationRequested(()=>{clearTimeout(t);resolve();},{once:true});}); if(token.isCancellationRequested||!enabled)return[]; const cfg=vscode.workspace.getConfiguration('appleFm'),scope=cfg.get<string>('contextScope','nearby'),version=document.version,line=position.line,character=position.character,mine=++generation,controller=new AbortController(),cancel=()=>controller.abort(),listener=token.onCancellationRequested(cancel); status.text='Apple FM · generating'; const request:Request={id:requestId(),kind:'editor',language:document.languageId,...contextFor(document,position,scope)};
  try{const result=await backend.run(request,controller.signal); if(result.status!=='ok'){status.text=`Apple FM · ${result.status}${result.reason?` · ${result.reason}`:''}`;return[];} const current=vscode.window.activeTextEditor; if(mine!==generation||!enabled||token.isCancellationRequested||document.version!==version||!current||current.document.uri.toString()!==document.uri.toString()||current.selection.active.line!==line||current.selection.active.character!==character)return[]; status.text=`Apple FM · ${cfg.get<string>('backend','fm')}`; return[new vscode.InlineCompletionItem(result.insertText!,new vscode.Range(position,position))];}finally{listener.dispose();}
 }
}
export function activate(context:vscode.ExtensionContext):void{output=vscode.window.createOutputChannel('Apple FM');status=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right,100); const configure=()=>{const c=vscode.workspace.getConfiguration('appleFm'),kind=c.get<'fm'|'swift'>('backend','fm'),helper=c.get<string>('swiftHelperPath','')||`${context.extensionPath}/bin/apple-fm-helper`; backend=createBackend(kind,helper);status.text=`Apple FM · ${kind==='fm'?'CLI':'Swift'}`;}; enabled=vscode.workspace.getConfiguration('appleFm').get('enabled',true);configure();status.show(); const invalidate=()=>{generation++;backend.cancel();}; context.subscriptions.push(vscode.languages.registerInlineCompletionItemProvider({scheme:'*'},new Provider()),vscode.window.onDidChangeActiveTextEditor(invalidate),vscode.window.onDidChangeTextEditorSelection(invalidate),vscode.workspace.onDidChangeTextDocument(invalidate),vscode.workspace.onDidChangeConfiguration(e=>{if(e.affectsConfiguration('appleFm')){enabled=vscode.workspace.getConfiguration('appleFm').get('enabled',true);invalidate();configure();}}),vscode.commands.registerCommand('appleFm.enable',()=>{enabled=true;invalidate();vscode.workspace.getConfiguration('appleFm').update('enabled',true,vscode.ConfigurationTarget.Global)}),vscode.commands.registerCommand('appleFm.disable',()=>{enabled=false;invalidate();vscode.workspace.getConfiguration('appleFm').update('enabled',false,vscode.ConfigurationTarget.Global)}),vscode.commands.registerCommand('appleFm.requestSuggestion',()=>vscode.commands.executeCommand('editor.action.inlineSuggest.trigger')),status,output);}
export function deactivate():void{generation++;backend?.cancel();void backend?.dispose();}
